id: P009236
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1052
  title: དཔལ་ལྡན་དམག་ཟོར་མའི་དྲག་པོའི་གཏོར་ཆེན
  author: ''
  volumes:
    2876d857be5e4a7fb1ade88de759c48e:
      image_group_id: I1CZ1412
      title: ''
      volume_number: 1
      total_pages: 32
      base_file: v001.txt
