id: ID554E7D4
legacy_id: P009236
ocr_import_info:
  bdrc_scan_id: W1CZ1052
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T07:59:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:47:16.597209+00:00'
last_modified: 2022-08-31 02:47:25.226529
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1052
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1052
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ལྡན་དམག་ཟོར་མའི་དྲག་པོའི་གཏོར་ཆེན།
  author: དེ་མོ ༠༣་ལྷ་དབང་ཕྱོགས་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.5146903523063042
  ocr_word_median_confidence_index: 0.46000000834465027
quality: null
bases:
  I1CZ1412:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1412
      total_pages: 32
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1412.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.5146903523063042
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
